### ISSUE TITLE
Credentials cannot be evaluated by pressing on 'Evaluate' button of JSONataView

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/configuration-component#17]
**Description:** JSONataView 'Evaluate' button currently DOES NOT WORK FOR CREDENTIALS, so regardless of input into Credentials input field (valid/invalid) nothing is shown on UI:
![image](https://user-images.githubusercontent.com/36419533/103633695-c10f9780-4f4e-11eb-8318-62da243f8ce3.png)
IN case if input JSON is invalid error thrown after click on 'Verify' button

This could be fixed:
a) on platform side: fix JSONataView behavior in credentials (then another issue should be created)
b) on component side: change filed type, as 'Evaluate' button may confuse a user

**Comment by jhorbulyk** [comment]
Solution for case a) may be already recorded in this issue: https://github.com/elasticio/elasticio/issues/4946

**Comment by jhorbulyk** [comment]
Closing in favor of https://github.com/elasticio/elasticio/issues/5875
